package hibernate;
// Generated Sep 9, 2022 10:07:34 AM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int rlno;
     private String name;
     private String city;

    public Student() {
    }

    public Student(int rlno, String name, String city) {
       this.rlno = rlno;
       this.name = name;
       this.city = city;
    }
   
    public int getRlno() {
        return this.rlno;
    }
    
    public void setRlno(int rlno) {
        this.rlno = rlno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


